// Code generated by MockGen. DO NOT EDIT.
// Source: service/bycrypt.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBycrypt is a mock of Bycrypt interface.
type MockBycrypt struct {
	ctrl     *gomock.Controller
	recorder *MockBycryptMockRecorder
}

// MockBycryptMockRecorder is the mock recorder for MockBycrypt.
type MockBycryptMockRecorder struct {
	mock *MockBycrypt
}

// NewMockBycrypt creates a new mock instance.
func NewMockBycrypt(ctrl *gomock.Controller) *MockBycrypt {
	mock := &MockBycrypt{ctrl: ctrl}
	mock.recorder = &MockBycryptMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBycrypt) EXPECT() *MockBycryptMockRecorder {
	return m.recorder
}

// CheckPasswordHash mocks base method.
func (m *MockBycrypt) CheckPasswordHash(password, hash string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPasswordHash", password, hash)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckPasswordHash indicates an expected call of CheckPasswordHash.
func (mr *MockBycryptMockRecorder) CheckPasswordHash(password, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPasswordHash", reflect.TypeOf((*MockBycrypt)(nil).CheckPasswordHash), password, hash)
}

// HashPassword mocks base method.
func (m *MockBycrypt) HashPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockBycryptMockRecorder) HashPassword(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockBycrypt)(nil).HashPassword), password)
}
